---
name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 10.22.0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm ci
      - name: Commit files
        env:
          HUSKY_SKIP_HOOKS: 1 
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          VERSION=$(npx next-standard-version)
          _DESCRIPTION=$(npx standard-version --dry-run --silent | grep -v yarn | grep -v Done | grep -v "\-\-\-" | grep -v standard-version)
          echo >>$GITHUB_ENV _DESCRIPTION=$_DESCRIPTION
          echo >>$GITHUB_ENV VERSION=$VERSION
          sed -i "s/__version__ = .*/__version__ = \"${VERSION}\"/g" src/__init__.py
          git add src/__init__.py
          git commit --no-verify -m "chore(release): ${VERSION}"
          npm run release
          git tag -d v$VERSION
          git reset --soft HEAD~~ && git commit --no-verify --no-edit -m "chore(release): ${VERSION}"
          git tag v$VERSION
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: |
            ${{ env._DESCRIPTION }}
          draft: false
          prerelease: false
